demoproject/blogapp/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from django.views.generic import TemplateView


app_name = 'blogapp'
urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('allauth.urls')),
    # path('send-from-email/', views.SendFormEmail.as_view(), name='sendemail'),
    path('contact', views.contact, name='contact'),
    path('create', views.PostCreateView.as_view(), name='create'),
    path('thanks', views.thanks, name='thanks'),
    path('search', views.search, name='search'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete'),
    path('comment/<int:pk>', views.CommentCreateView.as_view(), name='comment'),
    path("comment_delete/<int:post_id>/<int:pk>", views.CommentDeleteView.as_view(), name='comment-delete'),
    path("userdashboard/", views.userdashboard, name='userdashboard'),
    path("profile/<int:pk>", views.ProfileUpdateView.as_view(), name='profile'),
    path('user_dashboard', views.signup, name='user_dashboard'),
    path('detail/<int:pk>', views.detail, name='post_detail')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demoproject/demoproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('allauth', include('allauth.urls')),
]

demoproject/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogTimeStamp(models.Model):
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now_add=True)

   class Meta:
      abstract = True


class Category(BlogTimeStamp):
   name = models.CharField(max_length=100)

   def __str__(self):
      return f"{self.name}"


class Post(BlogTimeStamp):
   author = models.ForeignKey(User, on_delete=models.CASCADE)
   title = models.CharField(max_length=100)
   content = models.TextField(max_length=2000, null=True, blank=True)
   slug = models.SlugField(max_length=1000, null=True, blank=True)
   image = models.ImageField(upload_to='images', null=True, blank=True)
   posted_on = models.DateTimeField(auto_now=True)
   category = models.ManyToManyField(Category)

   def __str__(self):
      return f'{self.title}'


class Comment(BlogTimeStamp):
   post = models.ForeignKey(Post, on_delete=models.CASCADE)
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   body = models.TextField(max_length=100)
   posted_on = models.DateTimeField(auto_now=True)

   def __str__(self):
      return 'Comment by {}'.format(self.user)


class Profile(BlogTimeStamp):
   user = models.OneToOneField(User, on_delete=models.CASCADE)
   contact = models.IntegerField(null=True, blank=True)
   picture = models.ImageField(upload_to='media/', null=True, blank=True)
   bio = models.TextField(null=True, blank=True)

   def __str__(self):
      return f'{self.user}'

demoproject/blogapp/forms.py
from django import forms
from .models import Post, Comment, Profile
# from django.contrib.auth.forms import UserCreationForm


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'category', 'author']
        widgets = {'author': forms.HiddenInput()}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['user', 'body', 'post']
        widgets = {
            'user': forms.HiddenInput(),
            'post': forms.HiddenInput()
            }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user', 'picture', 'bio']
        widgets = {
            'user': forms.HiddenInput(),
            }

demoproject/blogapp/views.py
import email
from email import message
from django.urls import reverse_lazy, reverse
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Comment, Post, Profile
from .forms import PostForm, CommentForm, ProfileForm
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
# from django.contrib import messages
# # from django.contrib.auth.decorators import login_required
# from operator import is_not
# from django.http import HttpResponseRedirect


def home(request):
    Post_list = Post.objects.all()
    paginator = Paginator(Post_list, 2)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    return render(request, 'home/home.html', {'page_obj': page_obj})


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = "/thanks"

    def get_initial(self):
        initial = super(PostCreateView, self).get_initial()
        initial = initial.copy()
        initial['author'] = self.request.user.pk
        return initial


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "blogapp/post_form.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

    success_url = "/thanks"


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blogapp:home')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class CommentCreateView(LoginRequiredMixin, CreateView):
    template_name = "blogapp/comment.html"
    model = Comment
    form_class = CommentForm

    def get_initial(self):
        initial = super(CommentCreateView, self).get_initial()
        initial = initial.copy()
        initial['user'] = self.request.user.pk
        initial['post'] = self.kwargs['pk']
        return initial

    def get_context_data(self, **kwargs):
        context = super(CommentCreateView, self).get_context_data(**kwargs)
        context['comments'] = self.model.objects.filter(post_id=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse('blogapp:comment', kwargs={'pk': self.kwargs['pk']})


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        return reverse_lazy('blogapp:comment', kwargs={'pk': self.kwargs['post_id']})

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user


class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "blogapp/profile_form.html"
    success_url = reverse_lazy('blogapp:userdashboard')


def profile(request):
    return render(request, 'home/profile.html')


def detail(request, pk):
    post = Post.objects.get(id=pk)
    return render(request, 'home/detail.html', {'post': post})


def signup(request):
    return render(request, 'home/signup.html')


def contact(request):
    if request.method == "POST":
        email = request.POST.get('email')
        message = request.POST.get('message')

        send_mail(
            'subject ',
            'test',
            'baghelkriti@gmail.com', #from
            ['admin@gmail.com'], #to 
            fail_silently=False,
        )
    return render(request, 'home/contact.html')


def userdashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.filter(author=request.user)
        return render(request, 'home/userdashboard.html', {'posts': posts})


def search(request):
    q = request.GET['q']
    allPosts = Post.objects.filter(title__icontains=q)
    params = {'allPosts': allPosts}
    return render(request, 'home/search.html', params)


def thanks(request):
    return render(request, 'home/thanks.html')

demoproject/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <link href='{%static 'css/style.scc'}'>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{% block title %} blogNation{% endblock title %}</title>
  </head>
  
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <a class="navbar-brand" href="/">blogNation</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogapp:contact' %}">Contact us</a>
            </li>
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">login</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">logout</a>
            </li>
            {% endif %}
            <li class="nav-item">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Blogs</a>
                <div class="dropdown-menu">  
                <a class="dropdown-item" href="{% url 'blogapp:create' %}">Post a Blog</a> 
              </div>
          </ul>
          <form method="get" action="{% url 'blogapp:search' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button href="{% url 'blogapp:search' %}" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          {%if user.is_authenticated%}
          <a href="{% url 'blogapp:userdashboard' %}" target"blank" class="btn btn-outline-success m-2 my-sm-0" type="submit">User profile</a>
        {%endif%}
        </div>
      </nav>
      <img src='{%static "images/bg-image.jpeg"%}'>
      {% block body %} 
      {% endblock  %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
  </body>
</html>

demoproject/templates/blogapp/comment.html
{%extends 'base.html'%}

{% block body %}
<form class = "container my-3" action="" method="post">
  {%csrf_token%}
  {{form.as_p}}
  <input type="submit" value="submit">
</form>
<h2>Active comments</h2>
<h3>{{ comments.count }} comments</h3>
<ul>
  {% if perms.blogapp.add_post and user == post.author %}
  {% elif user.is_authenticated %}
  {% for comment in comments %}
  <div class="comments" style="padding: 10px;">
    <p class="font-weight-bold">
      <span class=" text-muted font-weight-normal">{{ comment.user }}</span></br>
      <span class=" font-weight-normal">{{ comment.body }}</span></br>
      <span class=" text-muted font-weight-normal">{{ comment.posted_on }}</span>
      <a class="btn btn-primary" href="{% url 'blogapp:comment-delete' comment.post.pk comment.pk %}" role="button">delete comment</a>
    </p>
  </div>
  {% endfor %}
  {%else%}
  <div class="container m-5" align="center">
    <h1>Login to Comment</h1>
    <a type="button" class="btn btn-secondary" href="{% url 'account_login' %}">login</a> 
  </div> 
</ul>
{%endif%}

{% endblock  %}

demoproject/templates/blogapp/comment_confirm_delete.html
{%extends 'base.html'%}

{% block body %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete this comment"{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock  %}

demoproject/templates/blogapp/comment_form.html
{%extends 'base.html'%}

{% block body %}


{% endblock  %}

demoproject/templates/blogapp/post_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

demoproject/templates/blogapp/post_form.html
{%extends 'base.html'%}

{% block body %}

<form class = "container my-2" action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    
    {{form.as_p}}
    <input type="submit" value="submit">
    
    {% comment %} <div class="container m-5" align="center">
        <h1>This is another users post</h1>
      </div> {% endcomment %}
   
</form>

{% endblock  %}

demoproject/templates/blogapp/profile_form.html
{%extends 'base.html'%}

{% block body %}

<form class = "container my-2" action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    
    {{form.as_p}}
    <input type="submit" value="submit">
</form>

{% endblock  %}

demoproject/templates/home/bloghome.html
{%extends 'base.html'%}

{% block body %}
</br>
<h2 align="center">Articles by blogNation:</h2>
<ul>
  {% for post in page_obj %}
    <li>
      <a href="{% url 'blogapp:post_detail' post.pk %}">
        {{ post.title|upper }}
        {% for c in post.category.all %}
          {{ c.name }}
        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">Article  by {{post.author}}</strong>
                <h3 class="mb-0">{{post.title}}</h3>
                <div class="mb-1 text-muted">{{post.posted_on}}</div>
                <p class="card-text mb-auto">{{post.content}}</p>
                <div class="my-2">
                    <a href="{% url 'blogapp:comment' %}" role="button" class="btn btn-primary" >Add a comment</a>
                    <a href="{% url 'blogapp:post_detail' post.pk%}" role="button" class="btn btn-primary" >Continue reading</a>
                </div>
          </div>
            <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                </svg>
            </div>
          </div>
        </div>
        {% endfor %}
      </a>
    </li>
  {% endfor %}
</ul>

<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
 

 {% endblock %}

demoproject/templates/home/contact.html
{%extends 'base.html'%}

{% block body %}
<h1 align="center"> Contact us </h1>
<div class="container my-2">
<form action="{%url 'blogapp:thanks' %}" id="contact-form" role="form" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="email" placeholder="Enter email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="content" class="form-label">Discribe your issue:</label>
        <textarea class="form-control" name="mess" id="content" rows="3"></textarea>               
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock  %}

demoproject/templates/home/create.html
{%extends 'base.html'%}

{% block body %}


{% endblock  %}

demoproject/templates/home/delete.html
{%extends 'base.html'%}

{% block body %}


{% endblock  %}

demoproject/templates/home/detail.html
{%extends 'base.html'%}
{%block title%}Detail{%endblock title%}
<h1> This is Blog detail</h1>
{% block body %}
<div class="container my-5" align="center">
<p>Article by: {{ post.author }}</p>
<p>{{ post.posted_on }}</p>
<h1>{{ post.title }}</h1>

{% if post.image %}
<img src={{post.image.url}} width="300" height="300"/>
{% endif %}

<p>{{ post.content }}</p>
<p>{{ post.slug }}</p>

<a href="{% url 'blogapp:update' post.pk %}" role="button" class="btn btn-outline-primary" >Edit</a>
<a href="{% url 'blogapp:delete' post.pk %}" role="button" class="btn btn-outline-primary" >Delete</a></br>
<div>
<a href="{% url 'blogapp:comment' post.pk %}" role="button" class="btn btn-secondary btn-lg btn-block dark my-2" >Read Comments</a>
</div>
</div>
{% endblock  %}

demoproject/templates/home/home.html
{%extends 'base.html'%}


{% block body %}
<div class="container m=3">
  <div <div
  class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/new/slides/003.webp');"
>
    <h1 class="display-4">Welcome to blogNation</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="/create" role="button">Post a Blog</a>
    
    
  </div>
</div>
<h1> Featured Blog Posts:</h1>

{% comment %} pagination  {% endcomment %}
<ul>
  {% for post in page_obj %}
    <li>
      <a href="{% url 'blogapp:post_detail' post.pk %}">
        {{ post.title|upper }}
        {% for c in post.category.all %}
          {{ c.name }}
        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">Article  by: {{post.author}}</strong>
                <h3 class="mb-0">{{post.title}}</h3>
                <div class="mb-1 text-muted">{{post.posted_on}}</div>
                {% comment %} <p class="card-text mb-auto">{{post.image}}</p> {% endcomment %}
                <p class="card-text mb-auto">{{post.content}}</p>
                <a href="{% url 'blogapp:post_detail' post.pk%}" role="link" class="btn-outline-dark">Continue reading...</a>
                <div class="my-2">
                  <a href="{% url 'blogapp:comment' post.pk %}" role="button" class="btn btn-primary my-2" >Add a comment</a>
                </div>                
        </div>
            <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" preserveAspectRatio="xMidYMid slice" role="img">
                    <title>Placeholder</title>
                    {% comment %} <img src={{post.image.url}} width="300" height="300"/> {% endcomment %}
                </svg>
            </div>
          </div>
        </div>
        {% endfor %}
      </a>
    </li>
  {% endfor %}
</ul>

<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>

{% comment %} card {% endcomment %}

 {%for post in allPosts%}
<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
  <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary">Article  by {{post.author}}</strong>
      <h3 class="mb-0">{{post.title}}</h3>
      <div class="mb-1 text-muted">{{post.posted_on}}</div>
      <p class="card-text mb-auto">{{post.content}}</p>
</div>
  <div class="col-auto d-none d-lg-block">
      <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
      </svg>
  </div>
  </div>
</div>
{%endfor%} 

{% endblock  %}

demoproject/templates/home/login_reminder.html
{%extends 'base.html'%}

{% block body %}
<div class="container m-5" align="center"> 

<h2>Please Login first </h2></br>

<a type="button" class="btn btn-secondary" href="{% url 'account_login' %}">login</a> 
</div>
{% endblock  %}

demoproject/templates/home/profile.html
{%extends 'base.html'%}

{% block body %}

{% endblock  %}

demoproject/templates/home/search.html
{% extends 'base.html' %}
{%  load static %}
{% block title %} Search Results: {% endblock title %}

{% block body %}

<h1 align="center"> Articles by blogNation:</h1>
<div class="container my-3">
    <h2>Search results : </h2>
    {% if allPosts|length < 1 %}
   <h4>No search results</h4>
   <p>Your search query: <b>{{q}}</b> Did not match.</p> 
    <p>Make sure that all words are spelled correctly.</p>
    <p>Try more general keywords.</p>
    <p>Try fewer keywords.</p>
    <p>Try different keywords.</p>
    {% endif %}
    {% for post in allPosts  %}
<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
        <strong class="d-inline-block mb-2 text-primary">Article  by {{post.author}}</strong>
        <h3 class="mb-0">{{post.title}}</h3>
        <div class="mb-1 text-muted">{{post.posted_on}}</div>
        <p class="card-text mb-auto">{{post.content}}</p>
        <div class="my-2">
            <a href="{% url 'blogapp:comment' post.pk%}" role="button" class="btn btn-primary" >Add a comment</a>
            <a href="{% url 'blogapp:post_detail' post.pk%}" role="button" class="btn btn-primary" >Continue reading</a>
        </div>
</div>
    <div class="col-auto d-none d-lg-block">
        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
        </svg>
    </div>
    </div>
</div>
{% endfor %}
</div>
{% endblock  %}

demoproject/templates/home/signup.html
{%extends 'base.html'%}

{% block body %}

{% endblock %}

demoproject/templates/home/thanks.html
{%extends 'base.html'%}

{% block body %}
<h1> Form submitted !!!!</h1>

{% endblock  %}

demoproject/templates/home/update.html
{%extends 'base.html'%}

{% block body %}


{% endblock  %}

demoproject/templates/home/userdashboard.html
{%extends 'base.html'%}
{%load static%}
{% block body %}
<h3 class="my-5" align="center">User Dashboard page</h3>
{% if user.is_authenticated%}
<div class="col=sm-10 m-5 p-5">
  {% comment %} user profile {% endcomment %}
  <div class="card mb-3">
    <img  style="height:300px;width:350px;" src="http://127.0.0.1:8000/media/media/image2.jpg">
    <div class="card-body" align="center">
      <h5 class="card-title">{{user.username}}</h5>
      <p class="card-text">{{user.profile.bio}}</p>
      <a href="{% url 'blogapp:profile' user.pk %}" target"blank" class="btn btn-secondary m-2 my-sm-0" type="submit">Edit your profile</a>
    </div>
  </div>
  {% endif %}

  {% comment %} blogs posted by the user {% endcomment %}
  {%if posts%}
<table class="table table-hover table-dark">
  <thead>
     <tr class="text-center">
      {% comment %} <th scope="col" style="width:2%">ID</th> {% endcomment %}
      <th scope="col" style="width:2%">Username</th>
      <th scope="col" style="width:2%">Posted on</th>
      <th scope="col" style="width:2%">Category</th>
      <th scope="col" style="width:2%">Title</th>
      <th scope="col" style="width:2%">Content</th>
      <th scope="col" style="width:2%">Actions</th>
    </tr> 
  </thead>
  <tbody>
    {%for post in posts%}
    <tr align="center">
      <td>{{ post.author}}</td>
      <td>{{ post.posted_on }}</td>
      <td>{{ post.category }}</td>
      <td>{{ post.title }} <img src={{post.image.url}} width="50" height="50"/></td>
      <td>{{ post.content }}</br><a href="{% url 'blogapp:post_detail' post.pk%}" class="stretched-link">Continue reading...</a></td>
      <td>
        <div class="btn-group" role="group" aria-label="Basic example">
          <a type="button" href="{% url 'blogapp:update' post.pk%}" class="btn btn-secondary">Edit</a> 
          <a type="button" href="{% url 'blogapp:delete' post.pk%}" class="btn btn-secondary">Delete</a> 
         

        </div>
    </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% else %}
<h4> No records</h4>
{% endif %}
<div class="container mb-5" align="center">
  <a href="{% url 'blogapp:create' %}" target"blank" class="btn btn-secondary" type="submit">Create more blogs</a>
</div>
{% endblock %}

templates/home/comment.html
{%extends 'base.html'%}

{% block body %}


{% endblock  %}

templates/home/create.html
{%extends 'base.html'%}

{% block body %}

adding model form in it 
{% endblock  %}